let data = {
  module: [
    'Biểu đồ thống kê',
    'Quản lí cho thuê',
    'Quản lí công việc',
    'Quản lí khách thuê',
    'Quản lí thu',
    'Danh mục tài sản',
    'Báo cáo',
    'Quản lí Dự án',
    'Quản lí tòa nhà',
    'Cài đặt người dùng',
  ],
  tables: [
    'Danh sách dashboard',
    'Hợp đồng',
    'Lịch sử thanh lý HĐ',
    'Chốt điện nước',
    'Thu phí',
    'Bảo chì sửa chữa',
    'Công việc thực hiện',
    'Khách thuê',
    ' Tương tác khách thuê',
    'Thông báo',
    'Lý do thu',
    'Danh sách phiếu thu',
    'Lập phiếu thu',
    'Tài sản',
    'Nhà sản xuất',
    'Loại tài sản',
    'Đơn vi',
    'Báo cáo thuê',
    'Báo cáo thu',
    'Báo cáo điện nước',
    'Báo cáo tài sản',
    'Dự án',
    'Tòa nhà',
    'Tầng',
    'Loại phòng',
    'Dịch vụ dự án',
    'Phòng',
    'Người dùng ',
    'Chức vụ',
    'Phân quyền',
  ],
  permissions: [
    'dash-board-list',
    'dash-board-total-bed',
    'dash-board-month-user',
    'hop-dong-list',
    'project-list',
    'building-list',
    'hop-dong-add',
    'hop-dong-detail',
    'hop-dong-edit',
    'hop-dong-delete',
    'hop-dong-print',
    'hop-dong-change-bed',
    'hop-dong-collect-deposit',
    'hop-dong-history-invoice-list',
    'hop-dong-history-invoice-edit',
    'history-contract-list',
    'project-list',
    'history-contract-edit',
    'electricity-water-list',
    'project-list',
    'building-list',
    'electricity-water-add',
    'electricity-water-detail',
    'invoice-contract-list',
    'project-list',
    'building-list',
    'invoice-contract-add',
    'invoice-contract-edit',
    'invoice-month-list',
    'invoice-month-add',
    'invoice-pay',
    'invoice-month-edit',
    'repair-list',
    'repair-add',
    'repair-edit',
    'repair-status-edit',
    'repair-delete',
    'task-list',
    'task-add',
    'task-edit',
    'task-delete',
    'task-detail',
    'task-status-edit',
    'tenant-list',
    'tenant-edit',
    'tenant-add',
    'Interactive-list',
    'Interactive-add',
    'Interactive-edit',
    'Interactive-delete',
    'Interactive-detail',
    'Interactive-print',
    'Notify-list',
    'Notify-add',
    'Notify-edit',
    'Notify-delete',
    'Notify-detail',
    'Notify-print',
    'reasons-list',
    'reasons-add',
    'reasons-edit',
    'reasons-delete',
    'reasons-detail',
    'reasons-print',
    'receipts-list',
    'receipts-edit',
    'Receipt-add',
    'asset-list',
    'asset-add',
    'asset-edit',
    'asset-delete',
    'asset-detail',
    'asset-print',
    'producer-list',
    'producer-add',
    'producer-edit',
    'producer-delete',
    'producer-detail',
    'producer-print',
    'type-asset-list',
    'type-asset-add',
    'type-asset-edit',
    'type-asset-delete',
    'type-asset-detail',
    'type-asset-print',
    'unit-list',
    'unit-add',
    'unit-edit',
    'unit-delete',
    'unit-detail',
    'unit-print',
    'rental-status',
    'tenants',
    'contract-history',
    'report-all',
    'report-service-index',
    'report-project-service',
    'asset-inventory',
    'maintenance-repair',
    'project-list',
    'type-room-list',
    'project-service-list',
    'project-add',
    'project-edit',
    'project-delete',
    'project-detail',
    'project-print',
    'building-list',
    'project-list',
    'building-add',
    'building-edit',
    'building-delete',
    'building-detail',
    'type-room-list',
    'room-list',
    'floor-list',
    'building-print',
    'floor-list',
    'floor-add',
    'floor-edit',
    'floor-delete',
    'floor-detail',
    'floor-print',
    'type-room-list',
    'type-room-add',
    'type-room-edit',
    'type-room-delete',
    'type-room-detail',
    'type-room-print',
    'project-service-list',
    'project-service-add',
    'project-service-edit',
    'project-service-delete',
    'project-service-detail',
    'project-service-print',
    'room-list',
    'room-add',
    'room-edit',
    'room-delete',
    'room-detail',
    'room-print',
    'user-list',
    'user-add',
    'user-edit',
    'user-delete',
    'user-detail',
    'user-print',
    'role-list',
    'role-add',
    'role-edit',
    'role-delete',
    'role-detail',
    'permission-list',
    'permission-add',
    'permission-detail',
  ],
};
