<?php
return [
    "schools" => [
        "Đại học Bách khoa Hà Nội,Đại học Công đoàn,",
        "Đại học Công nghệ - ĐHQG Hà Nội,",
        "Đại học Công nghệ Giao thông vận tải,",
        "Đại học Công nghệ và Quản lý Hữu Nghị,",
        "Đại học Công nghiệp Dệt may Hà Nội,",
        "Đại học Công nghiệp Hà Nội,",
        "Đại học Công nghiệp Việt Hung,",
        "Đại học Điện lực,",
        "Đại học Dược Hà Nội,",
        "Đại Học Giáo dục - ĐHQG Hà Nội,",
        "Đại học Giao thông vận tải,",
        "Đại học Hà Nội,",
        "Đại Học Khoa học Tự nhiên - ĐHQG Hà Nội,",
        "Đại học Khoa học và Công nghệ Hà Nội,",
        "Đại Học Khoa học Xã hội và Nhân văn - ĐHQG Hà Nội,",
        "Đại học Kiểm sát Hà Nội,",
        "Đại học Kiến trúc Hà Nội,",
        "Đại học Kinh tế - ĐHQG Hà Nội,",
        "Đại học Kinh tế Kỹ thuật Công nghiệp Hà Nội,",
        "Đại học Kinh tế Quốc dân,",
        "Đại học Lâm nghiệp,",
        "Đại học Lao động Xã hội,",
        "Đại học Luật Hà Nội,",
        "Đại học Mỏ Địa chất Hà Nội,",
        "Đại học Mở Hà Nội,",
        "Đại Học Mở Hà Nội,",
        "Đại học Mỹ thuật Công nghiệp,",
        "Đại học Mỹ thuật Việt Nam,",
        "Đại học Ngoại ngữ - ĐHQG Hà Nội,",
        "Đại học Ngoại thương,",
        "Đại học Nội vụ Hà Nội,",
        "Đại học Quốc gia Hà Nội,",
        "Đại học Sân khấu Điện ảnh,",
        "Đại học Sư phạm Hà Nội,",
        "Trường Đại học Sư phạm Hà Nội,",
        "Đại học Sư phạm Nghệ thuật Trung ương Hà Nội,",
        "Đại học Sư phạm Thể dục thể thao Hà nội,",
        "Đại học Tài chính - Ngân hàng Hà Nội,",
        "Đại học Tài nguyên và Môi trường Hà Nội,",
        "Đại học Thành Đô\tTDD",
        "Đại học Thủ đô Hà Nội\tC,",
        "Đại học Thương mại,",
        "Đại học Thủy lợi,",
        "Đại học Văn hóa Hà Nội,",
        "Đại học VinUni,",
        "Đại học Xây dựng,",
        "Đại học Y Hà Nội,",
        "Đại học Y tế Công cộng,",
        "Học viện Âm nhạc Quốc gia Việt Nam,",
        "Học viện Báo chí Tuyên truyền,",
        "Học viện Chính sách và Phát triển,",
        "Học viện Công nghệ Bưu chính Viễn thông,",
        "Học viện Hành chính Quốc gia,",
        "Học Viện Hậu Cần,",
        "Học viện Khoa học Quân sự,",
        "Học viện Kỹ thuật Mật mã,",
        "Học viện Ngân hàng,",
        "Học viện Ngoại giao,",
        "Học viện Nông nghiệp Việt Nam,",
        "Học viện Phụ nữ Việt Nam,",
        "Học viện Quản lý Giáo dục,",
        "Học viện Tài chính,",
        "Học viện Thanh Thiếu niên Việt Nam,",
        "Học viện Tòa án,",
        "Học viện Y Dược học cổ truyền Việt Nam,",
        "Khoa Luật - ĐHQG Hà Nội,",
        "Khoa Quốc tế - ĐHQG Hà Nội,",
        "Khoa Y Dược - ĐHQG Hà Nội"
    ]
];
